import { createContext, useContext, useState, useCallback, useEffect, useRef, useMemo } from 'react'
import { apiGet, apiPost } from '../services/api'
import { useToast } from './ToastContext'

// ── Context ─────────────────────────────────────────────────────────────────

const LLMContext = createContext(null)

// Retry delays (ms) after each consecutive fetch failure
const RETRY_DELAYS = [2000, 5000, 15000]

// ── Provider ────────────────────────────────────────────────────────────────

export function LLMProvider({ children }) {
  const { showSuccess, showError } = useToast()

  const [status, setStatus] = useState(null)
  const [loading, setLoading] = useState(false)
  const [lastResult, setLastResult] = useState(null)
  const [error, setError] = useState(null)

  const retryTimerRef = useRef(null)

  // ── Fetch LLM status with automatic retry on failure ───────────────────
  const fetchWithRetry = useCallback(async (attempt = 0) => {
    try {
      const data = await apiGet('/llm/status')
      setStatus(data)
    } catch {
      if (attempt < RETRY_DELAYS.length) {
        retryTimerRef.current = setTimeout(
          () => fetchWithRetry(attempt + 1),
          RETRY_DELAYS[attempt],
        )
      } else {
        setStatus({ available: false, provider: 'none', model: '', skills: [] })
      }
    }
  }, [])

  // Public fetchStatus — resets retries and re-fetches from scratch
  const fetchStatus = useCallback(() => {
    if (retryTimerRef.current) {
      clearTimeout(retryTimerRef.current)
      retryTimerRef.current = null
    }
    setStatus(null)
    fetchWithRetry(0)
  }, [fetchWithRetry])

  // Fetch status on mount; clean up pending retry on unmount
  useEffect(() => {
    fetchWithRetry(0)
    return () => {
      if (retryTimerRef.current) clearTimeout(retryTimerRef.current)
    }
  }, [fetchWithRetry])

  // ── Availability check ──────────────────────────────────────────────────
  // Returns true  — LLM confirmed available
  // Returns false — LLM confirmed unavailable
  // Returns null  — status not yet known (still loading / retrying)
  const isAvailable = useCallback(() => {
    if (status === null) return null
    return status?.available ?? false
  }, [status])

  // ── Execute a generic skill ─────────────────────────────────────────────
  const executeSkill = useCallback(async (skillId, prompt, context = {}) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/execute', {
        skill_id: skillId,
        prompt,
        context,
      })
      setLastResult(data)
      showSuccess('AI task completed')
      return data
    } catch (err) {
      const msg = err.message || 'LLM request failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Generate a new overlay element ──────────────────────────────────────
  const generateElement = useCallback(async (prompt, section, presetId, existingElements = []) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/overlay/generate', {
        prompt,
        section,
        preset_id: presetId,
        existing_elements: existingElements,
      })
      setLastResult(data)
      showSuccess(data.explanation || 'Element generated by AI')
      return data
    } catch (err) {
      const msg = err.message || 'Element generation failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Augment an existing overlay element ─────────────────────────────────
  const augmentElement = useCallback(async (prompt, section, presetId, elementId, options = {}) => {
    const { silent = false } = options
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/overlay/augment', {
        prompt,
        section,
        preset_id: presetId,
        element_id: elementId,
      })
      setLastResult(data)
      if (!silent) {
        showSuccess(data.explanation || 'Element updated by AI')
      }
      return data
    } catch (err) {
      const msg = err.message || 'Element augmentation failed'
      setError(msg)
      if (!silent) {
        showError(msg)
      }
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Run editorial refinement on highlights ──────────────────────────────
  const runEditorial = useCallback(async (prompt, timeline, scoredEvents, metrics, raceInfo) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/editorial', {
        prompt,
        timeline,
        scored_events: scoredEvents,
        metrics,
        race_info: raceInfo,
      })
      setLastResult(data)
      showSuccess('Editorial refinement complete')
      return data
    } catch (err) {
      const msg = err.message || 'Editorial refinement failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Context value ───────────────────────────────────────────────────────
  const value = useMemo(() => ({
    status,
    loading,
    lastResult,
    error,
    fetchStatus,
    isAvailable,
    executeSkill,
    generateElement,
    augmentElement,
    runEditorial,
  }), [status, loading, lastResult, error, fetchStatus, isAvailable,
       executeSkill, generateElement, augmentElement, runEditorial])

  return (
    <LLMContext.Provider value={value}>
      {children}
    </LLMContext.Provider>
  )
}

// ── Hook ────────────────────────────────────────────────────────────────────

/**
 * Access the LLM integration context.
 *
 * Provides:
 *   - ``status`` — current provider availability info
 *   - ``loading`` — true during any LLM API call
 *   - ``isAvailable()`` — true/false/null (null = still determining)
 *   - ``generateElement(prompt, section, presetId, existingElements)``
 *   - ``augmentElement(prompt, section, presetId, elementId)``
 *   - ``runEditorial(prompt, timeline, scoredEvents, metrics, raceInfo)``
 *   - ``executeSkill(skillId, prompt, context)``
 */
export function useLLM() {
  const ctx = useContext(LLMContext)
  if (!ctx) {
    // Fallback avoids hard-crashing screens that render before provider wiring settles.
    return {
      status: { available: false, provider: 'none', model: '', skills: [] },
      loading: false,
      lastResult: null,
      error: 'LLMProvider unavailable',
      fetchStatus: () => {},
      isAvailable: () => false,
      executeSkill: async () => null,
      generateElement: async () => null,
      augmentElement: async () => null,
      runEditorial: async () => null,
    }
  }
  return ctx
}
