import { createContext, useContext, useState, useCallback, useEffect, useMemo } from 'react'
import { apiGet, apiPost } from '../services/api'
import { useToast } from './ToastContext'

// ── Context ─────────────────────────────────────────────────────────────────

const LLMContext = createContext(null)

// ── Provider ────────────────────────────────────────────────────────────────

export function LLMProvider({ children }) {
  const { showSuccess, showError } = useToast()

  const [status, setStatus] = useState(null)
  const [loading, setLoading] = useState(false)
  const [lastResult, setLastResult] = useState(null)
  const [error, setError] = useState(null)

  // ── Fetch LLM availability status ───────────────────────────────────────
  const fetchStatus = useCallback(async () => {
    try {
      const data = await apiGet('/llm/status')
      setStatus(data)
    } catch {
      setStatus({ available: false, provider: 'none', model: '', skills: [] })
    }
  }, [])

  // Fetch status on mount
  useEffect(() => {
    fetchStatus()
  }, [fetchStatus])

  // ── Availability check ──────────────────────────────────────────────────
  const isAvailable = useCallback(() => {
    return status?.available ?? false
  }, [status])

  // ── Execute a generic skill ─────────────────────────────────────────────
  const executeSkill = useCallback(async (skillId, prompt, context = {}) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/execute', {
        skill_id: skillId,
        prompt,
        context,
      })
      setLastResult(data)
      showSuccess('AI task completed')
      return data
    } catch (err) {
      const msg = err.message || 'LLM request failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Generate a new overlay element ──────────────────────────────────────
  const generateElement = useCallback(async (prompt, section, presetId, existingElements = []) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/overlay/generate', {
        prompt,
        section,
        preset_id: presetId,
        existing_elements: existingElements,
      })
      setLastResult(data)
      showSuccess(data.explanation || 'Element generated by AI')
      return data
    } catch (err) {
      const msg = err.message || 'Element generation failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Augment an existing overlay element ─────────────────────────────────
  const augmentElement = useCallback(async (prompt, section, presetId, elementId) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/overlay/augment', {
        prompt,
        section,
        preset_id: presetId,
        element_id: elementId,
      })
      setLastResult(data)
      showSuccess(data.explanation || 'Element updated by AI')
      return data
    } catch (err) {
      const msg = err.message || 'Element augmentation failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Run editorial refinement on highlights ──────────────────────────────
  const runEditorial = useCallback(async (prompt, timeline, scoredEvents, metrics, raceInfo) => {
    setLoading(true)
    setError(null)
    try {
      const data = await apiPost('/llm/editorial', {
        prompt,
        timeline,
        scored_events: scoredEvents,
        metrics,
        race_info: raceInfo,
      })
      setLastResult(data)
      showSuccess('Editorial refinement complete')
      return data
    } catch (err) {
      const msg = err.message || 'Editorial refinement failed'
      setError(msg)
      showError(msg)
      return null
    } finally {
      setLoading(false)
    }
  }, [showSuccess, showError])

  // ── Context value ───────────────────────────────────────────────────────
  const value = useMemo(() => ({
    status,
    loading,
    lastResult,
    error,
    fetchStatus,
    isAvailable,
    executeSkill,
    generateElement,
    augmentElement,
    runEditorial,
  }), [status, loading, lastResult, error, fetchStatus, isAvailable,
       executeSkill, generateElement, augmentElement, runEditorial])

  return (
    <LLMContext.Provider value={value}>
      {children}
    </LLMContext.Provider>
  )
}

// ── Hook ────────────────────────────────────────────────────────────────────

/**
 * Access the LLM integration context.
 *
 * Provides:
 *   - ``status`` — current provider availability info
 *   - ``loading`` — true during any LLM API call
 *   - ``isAvailable()`` — quick check if LLM is configured
 *   - ``generateElement(prompt, section, presetId, existingElements)``
 *   - ``augmentElement(prompt, section, presetId, elementId)``
 *   - ``runEditorial(prompt, timeline, scoredEvents, metrics, raceInfo)``
 *   - ``executeSkill(skillId, prompt, context)``
 */
export function useLLM() {
  const ctx = useContext(LLMContext)
  if (!ctx) throw new Error('useLLM must be used within LLMProvider')
  return ctx
}
